Repository WildCodeSchool/orleans-0219-php-renoving-habitat, pull requests merged in 2019-06, with the labels that each got.

#4 Project init homepage
  assets/js/app.js
  assets/js/mapedImage.js
  assets/js/mapster.js
  assets/js/tooltipster.bundle.js
  assets/scss/app.scss
  assets/scss/homepage.scss
  assets/scss/tooltipster.bundle.scss
  composer.json
  composer.lock
  package-lock.json
  package.json
  public/assets/homepage_image/house_homepage.jpg
  public/css/style.css
  public/css/tooltipster.bundle.css
  public/js/beforeAfter.js
  public/js/mapedImage.js
  public/js/mapster.js
  public/js/tooltipster.bundle.js
  src/Controller/HomeController.php
  symfony.lock
  templates/base.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed by team member, reviewedby PO

#8 Dev fix2
  assets/js/app.js
  assets/js/mapedImage.js
  assets/js/mapster.js
  assets/js/tooltipster.bundle.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/homepage.scss
  assets/scss/tooltipster.bundle.scss
  package-lock.json
  package.json
  public/css/style.css
  public/css/tooltipster.bundle.css
  public/js/beforeAfter.js
  public/js/mapedImage.js
  public/js/mapster.js
  public/js/tooltipster.bundle.js
  templates/base.html.twig
  webpack.config.js
Labels: reviewedby PO

#12 Sprint01 us06 bons plans homepage
  templates/home/_good_deal_block.html.twig
  templates/home/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#14 Us08 sprint01 footer
  assets/scss/app.scss
  assets/scss/footer.scss
  public/assets/footer_image/renovlogo.png
  templates/base.html.twig
  templates/footer/index.html.twig
  templates/home/index.html.twig
  webpack.config.js
Labels: Correction done, reviewedby PO

#13 S1 us2 navbar
  assets/js/app.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/navabar.scss
  package.json.orig
  public/assets/images/logoRenovingHabitat.png
  templates/base.html.twig
  templates/navbar.html.twig
  yarn.lock
Labels: Correction done, reviewedby PO

#15 fix de bons plans admin
  src/Controller/GoodDealController.php
  src/Form/GoodDealType.php
  templates/good_deal/_form.html.twig
  templates/good_deal/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#11 map sur homepage
  assets/js/app.js
  assets/js/map.js
  assets/scss/app.scss
  assets/scss/home_map.scss
  package.json
  public/assets/homepage_image/leaf-green.png
  public/assets/homepage_image/leaf-home.png
  public/assets/homepage_image/marker-icon.png
  templates/home/index.html.twig
  templates/map/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by team member, reviewedby PO

#16 Fix ok
  templates/base.html.twig
  templates/home/index.html.twig
  templates/layout_admin.html.twig
  templates/layout_visitor.html.twig
Labels: Reviewed by team member

#9 Us03 sprint01 home picture
  assets/js/mapResizer.js
  assets/js/mappedImage.js
  assets/scss/app.scss
  assets/scss/homepage.scss
  package-lock.json
  package.json
  templates/home/index.html.twig
  webpack.config.js
Labels: Reviewed by team member, reviewedby PO

#23 Sprint03 us18 formulaire recrutment file upload
  assets/js/fix_upload.js
  assets/scss/app.scss
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/RecruitmentController.php
  src/Entity/CvUpload.php
  src/Form/CvUploadType.php
  src/Repository/CvUploadRepository.php
  templates/base.html.twig
  templates/recruitment/email.html.twig
  templates/recruitment/show.html.twig
  webpack.config.js
Labels: Correction done, reviewedby PO
