Repository WildCodeSchool/orleans-0219-php-renoving-habitat, pull requests merged in 2019-07, with the labels that each got.

#24 Mon projet
  assets/images/mon_projet_image/chauffage.jpg
  assets/images/mon_projet_image/ravalement.jpg
  assets/images/mon_projet_image/salle_de_bain.jpg
  assets/images/mon_projet_image/terrassement.jpg
  assets/images/mon_projet_image/travaux_interieur.jpg
  assets/images/mon_projet_image/tuile.jpg
  assets/js/before_after_slider.js
  assets/js/map_resizer.js
  assets/js/mapped_image.js
  assets/js/mon_projet.js
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/homepage.scss
  assets/scss/mon_projet.scss
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/Controller/MyProjectController.php
  src/Entity/Bathroom.php
  src/Entity/EarthWork.php
  src/Entity/Facade.php
  src/Entity/Heating.php
  src/Entity/HouseWork.php
  src/Entity/MainWorkCategories.php
  src/Entity/MyProjectPersonal.php
  src/Entity/Roofing.php
  src/Form/BathroomType.php
  src/Form/EarthWorkType.php
  src/Form/FacadeType.php
  src/Form/HeatingType.php
  src/Form/HouseWorkType.php
  src/Form/MyProjectPersonalType.php
  src/Form/MyProjectType.php
  src/Form/RoofingType.php
  src/Service/MyProjectEmailSender.php
  templates/monProjet/email/email.html.twig
  templates/monProjet/index.html.twig
  webpack.config.js
Labels: changes requested, reviewedby PO

#27 Fix liens footer et navbar
  assets/scss/navbar.scss
  templates/footer/index.html.twig
  templates/navbar.html.twig
Labels: Reviewed by team member, reviewedby PO

#29 Sprint04 us18 nous recrutons
  assets/scss/app.scss
  assets/scss/recrutment.scss
  public/assets/images/croissance1.png
  public/assets/images/macon.png
  public/assets/images/ouvrier.png
  public/assets/images/perceuse.png
  public/assets/images/poignee.png
  public/assets/images/poseur.png
  public/assets/images/technico.jpg
  templates/footer/index.html.twig
  templates/recruitment/show.html.twig
Labels: Conflit fixed, Reviewed by team member

#30 Entreprise
  assets/images/main/bb.png
  assets/images/main/construction-men.png
  assets/images/partenaires/FFB.png
  assets/images/partenaires/Qualibat.png
  assets/images/partenaires/Sofinco.png
  assets/images/partenaires/anah.jpg
  assets/images/partenaires/caisse-retraite.jpg
  assets/images/partenaires/credit-dimpot.png
  assets/images/partenaires/plane.png
  assets/images/partenaires/ptz.png
  assets/scss/app.scss
  assets/scss/entreprise.scss
  src/Controller/EntrepriseController.php
  templates/entreprise/index.html.twig
  templates/footer/index.html.twig
  templates/navbar.html.twig
Labels: Conflit fixed, Reviewed by team member, reviewedby PO

#31 Fix dev
  package.json
  templates/footer/index.html.twig
  yarn.lock
Labels: Conflit fixed, Reviewed by team member, reviewedby PO

#34 Sprint05 nous recrutons fix
  assets/images/recrutment/macon.png
  assets/images/recrutment/poseur.png
  assets/images/recrutment/technico.jpg
  assets/scss/recrutment.scss
  public/assets/images/croissance1.png
  public/assets/images/ouvrier.png
  public/assets/images/perceuse.png
  public/assets/images/poignee.png
  templates/recruitment/show.html.twig
Labels: Reviewed by team member, reviewedby PO

#36 Fiv nav
  assets/js/app.js
  assets/scss/app.scss
  templates/base.html.twig
  templates/navbar.html.twig
Labels: Reviewed by team member, reviewedby PO

#35 House
  assets/images/homepage/house_couverture.png
  assets/images/homepage/house_interieur.png
  assets/images/homepage/house_isolation.png
  assets/images/homepage/house_menuiserie.png
  assets/images/homepage/house_ravalement.png
  assets/images/homepage/house_terrassement.png
  assets/scss/homepage.scss
  templates/home/index.html.twig
Labels: changes requested

#38 alignement et modif textes
  assets/scss/entreprise.scss
  templates/entreprise/index.html.twig
Labels: Reviewed by team member

#39 Fix foot
  assets/scss/footer.scss
  templates/footer/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#40 Fix cartes
  assets/images/homepage/house_int.png
  assets/images/homepage/house_rav.png
  templates/home/index.html.twig
Labels: Reviewed by team member

#41 Homepage fix
  assets/images/partenaires/gerondeau.jpg
  assets/images/partenaires/gerondeau.png
  assets/scss/homepage.scss
  assets/scss/navbar.scss
  assets/scss/renoving.scss
  templates/home/index.html.twig
Labels: Reviewed by team member

#44 Admin fix
  templates/security/reset_password.html.twig
Labels: Reviewed by team member, reviewedby PO

#45 Post dev fix1
  assets/scss/footer.scss
  assets/scss/navbar.scss
  assets/scss/nos_realisations.scss
  src/Controller/CustomerReviewController.php
  src/Controller/GoodDealController.php
  templates/base.html.twig
  templates/customer_review/index.html.twig
  templates/customer_review/show.html.twig
  templates/footer/index.html.twig
  templates/good_deal/index.html.twig
  templates/good_deal/show.html.twig
  templates/nos_realisations/index.html.twig
Labels: Reviewed by team member

#46 Ajout des liens actifs
  assets/scss/navbar.scss
  templates/navbar.html.twig
Labels: Reviewed by team member

#47 fixed the navbar dropdown hover
  assets/scss/navbar.scss
Labels: Reviewed by team member

#50 Post dev fix4
  assets/scss/_vars.scss
  assets/scss/mon_projet.scss
  assets/scss/nos_realisations.scss
  templates/monProjet/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#53 Title uniforme
  assets/scss/entreprise.scss
  assets/scss/homepage.scss
  assets/scss/mon_projet.scss
  assets/scss/nos_realisations.scss
  assets/scss/recrutment.scss
  assets/scss/renoving.scss
  templates/entreprise/index.html.twig
  templates/home/index.html.twig
  templates/je_renov/carpentry.html.twig
  templates/je_renov/cleaning.html.twig
  templates/je_renov/coverage.html.twig
  templates/je_renov/earthwork.html.twig
  templates/je_renov/indoor.html.twig
  templates/je_renov/insulation.html.twig
  templates/monProjet/index.html.twig
  templates/nos_realisations/index.html.twig
  templates/recruitment/show.html.twig
Labels: Reviewed by team member, reviewedby PO

#52 ajout minZoom et maxZoom sur la map
  assets/js/map.js
  assets/scss/home_map.scss
  templates/map/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#51 Fix style carousel before/after
  assets/images/homepage/left_arrow.png
  assets/images/homepage/right_arrow.png
  assets/js/before_after_slider.js
  assets/scss/_vars.scss
  assets/scss/homepage.scss
  templates/home/index.html.twig
Labels: Correction done, Reviewed by team member, reviewedby PO

#55 fix formulaire
  assets/scss/recrutment.scss
  src/Entity/CvUpload.php
  src/Form/CvUploadType.php
  templates/recruitment/show.html.twig
Labels: Correction done

#56 ajout texte explicatif des sinitres
  templates/je_renov/carpentry.html.twig
  templates/je_renov/cleaning.html.twig
  templates/je_renov/coverage.html.twig
  templates/je_renov/earthwork.html.twig
  templates/je_renov/indoor.html.twig
  templates/je_renov/insulation.html.twig
Labels: Reviewed by team member, reviewedby PO

#62 fix placeholder formulaire
  src/Form/CvUploadType.php
  src/Form/MyProjectPersonalType.php
  templates/monProjet/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#63 Orthographe
  src/Controller/RecruitmentController.php
  templates/entreprise/index.html.twig
  templates/home/index.html.twig
  templates/je_renov/carpentry.html.twig
  templates/je_renov/cleaning.html.twig
  templates/je_renov/coverage.html.twig
  templates/je_renov/earthwork.html.twig
  templates/je_renov/indoor.html.twig
  templates/je_renov/insulation.html.twig
  templates/monProjet/index.html.twig
  templates/recruitment/show.html.twig
Labels: Reviewed by team member, reviewedby PO

#64 Logo partenaires
  assets/images/partenaires/logo_eurochem.png
  assets/images/partenaires/logo_rockwool.png
  assets/images/partenaires/logo_zoplan.png
  assets/scss/homepage.scss
  templates/home/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#66 boutons je renov + fleche homepage
  assets/scss/homepage.scss
  assets/scss/renoving.scss
  templates/home/index.html.twig
  templates/je_renov_button/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#68 Fix responsive
  assets/scss/entreprise.scss
  assets/scss/footer.scss
  assets/scss/homepage.scss
  templates/CGVU/index.html.twig
  templates/entreprise/index.html.twig
  templates/footer/index.html.twig
  templates/home/index.html.twig
  templates/je_renov_circle/index.html.twig
  templates/monProjet/index.html.twig
  templates/nos_realisations/index.html.twig
  templates/recruitment/show.html.twig
Labels: Reviewed by team member, reviewedby PO

#71 Spelling
  templates/je_renov/carpentry.html.twig
  templates/je_renov/cleaning.html.twig
  templates/je_renov/coverage.html.twig
  templates/je_renov/earthwork.html.twig
  templates/je_renov/indoor.html.twig
  templates/je_renov/insulation.html.twig
Labels: Reviewed by team member, reviewedby PO

#72 added photos
  assets/images/nos_real_modal_img/ravalement/ravalement4.jpg
  assets/images/nos_real_modal_img/ravalement/ravalement5.jpg
  assets/images/nos_real_modal_img/salle_de_bain/sdb1.jpg
  assets/images/nos_real_modal_img/salle_de_bain/sdb2.jpg
  assets/images/nos_real_modal_img/toiture/toiture4.jpg
  templates/nos_realisations/modals.html.twig
Labels: Reviewed by team member, reviewedby PO

#75 Dev
  README.md
  assets/images/je_renov_images/chauffage.jpg
  assets/images/je_renov_images/cloture.jpg
  assets/images/je_renov_images/douche.jpg
  assets/images/je_renov_images/goudron.jpg
  assets/images/je_renov_images/toiture_zinc.jpg
  assets/images/je_renov_images/tuile_canal.jpg
  assets/images/je_renov_images/tuile_plate.jpg
  assets/images/nos_real_modal_img/ravalement/ravalement4.jpg
  assets/images/nos_real_modal_img/ravalement/ravalement5.jpg
  assets/images/nos_real_modal_img/salle_de_bain/sdb1.jpg
  assets/images/nos_real_modal_img/salle_de_bain/sdb2.jpg
  assets/images/nos_real_modal_img/toiture/toiture4.jpg
  assets/scss/renoving.scss
  composer.json
  composer.lock
  phpstan.neon
  src/Migrations/Version20190709084416.php
  symfony.lock
  templates/base.html.twig
  templates/guaranty/index.html.twig
  templates/home/index.html.twig
  templates/je_renov/carpentry.html.twig
  templates/je_renov/cleaning.html.twig
  templates/je_renov/coverage.html.twig
  templates/je_renov/earthwork.html.twig
  templates/je_renov/indoor.html.twig
  templates/je_renov/insulation.html.twig
  templates/je_renov_circle/index.html.twig
  templates/navbar.html.twig
  templates/nos_realisations/index.html.twig
  templates/nos_realisations/modals.html.twig
Labels: Reviewed by team member, reviewedby PO

#76 fix spelling
  templates/home/index.html.twig
Labels: Reviewed by team member, reviewedby PO

#77 Fix Flash Anchor
  assets/scss/recrutment.scss
  src/Controller/RecruitmentController.php
  templates/recruitment/show.html.twig
Labels: Reviewed by team member, reviewedby PO

#79 Responsive fix
  assets/scss/_vars.scss
  assets/scss/app.scss
  assets/scss/entreprise.scss
  assets/scss/homepage.scss
  assets/scss/mon_projet.scss
  assets/scss/nos_realisations.scss
  assets/scss/recrutment.scss
  assets/scss/renoving.scss
  templates/entreprise/index.html.twig
  templates/home/index.html.twig
  templates/je_renov/carpentry.html.twig
  templates/je_renov/cleaning.html.twig
  templates/je_renov/coverage.html.twig
  templates/je_renov/earthwork.html.twig
  templates/je_renov/indoor.html.twig
  templates/je_renov/insulation.html.twig
  templates/je_renov_button/index.html.twig
  templates/monProjet/index.html.twig
  templates/nos_realisations/index.html.twig
  templates/recruitment/show.html.twig
Labels: Reviewed by team member, reviewedby PO
